# 아래의 주요 key, secret 은 쿠버네티스의 secret 자원을 사용하여 실행 시점에 대체 시키겠다.

server:
  port: 8082

spring:
  redis:
  # 아래의 REDIS_HOST 는 deployment에서 정의한 env 변수명과 일치해야함.
    host: ${REDIS_HOST} # localhost
    port: 6379

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ordersystem
    username: ${DB_USERNAME} # root
    password: ${DB_PASSWORD} # 1234
    # spring에서 db로의 커넥션 개수 제한 -> 제한 안하면 터질 수 있다.
    # 기본적으로 대략 10개 가량의 커넥션이 1개의 서버에서 발생.
    tomcat:
      max-active: 5

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true

logging:
  level:
    root: info

jwt:
  expiration: 30
  secretKey: ${JWT_SECRET} # my_token_secret
  expirationRt: 14404
  secretKeyRt: ${JWT_SECRET_RT} # hackerton_secret

#aws s3 설정
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY} # 엑세스 키
      secret-key: ${AWS_SECRET_KEY} # 비밀 키
    region:
      static: ap-northeast-2
    s3:
      bucket: moori-file
