# 스크립트 문서를 만들 때에는 yml 이 표준이다.
apiVersion: v1
# 자원의 종류를 명시
kind: Pod
metadata:
  name: nginx-pod
  namespace: mooo
  # labels는 service의 라우팅 대상이 되는 이름
  # service의 selector.app을 통해 매핑
  labels:
    app: my-nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports: 
        - containerPort: 80